### ISSUE TITLE
TypeError when loading remote contexts

### ISSUE THREAD

**Issue by davidlj95** [blockchain-certificates/blockcerts-verifier#44]
# Issue
We are using external JSON-LD context.jsons in our certificates that add some data not included in  Blockcerts context.jsons.

## Symptoms
A `TypeError` is triggered when using another remote context rather than the default, cached ones ([Open Badges v2](https://w3id.org/openbadges/v2), [Blockcerts v2](https://w3id.org/blockcerts/v2), embedded context)

## Stacktrace
```
TypeError: i is not a function

      at i (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:268153)
      at e.RequestQueue.u [as _loader] (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:267523)
      at e.RequestQueue._loader [as add] (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:264385)
      at Function.i [as documentLoader] (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:330140)
      at documentLoader (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:260137)
      at r (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:313671)
      at o (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:312546)
      at o (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:313729)
      at i (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:249477)
      at i (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:250035)
      at Item.apply [as run] (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:158962)
      at run (node_modules/@blockcerts/cert-verifier-js/dist/verifier-es.js:1:158578)
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:628:19)
```

## Reproduce the issue
Change `test/fixtures/valid-certificate-example.json` Blockcerts context and use the [v2.1 one](https://w3id.org/blockcerts/v2.1):

```diff
-    "https://w3id.org/blockcerts/v2",
+    "https://w3id.org/blockcerts/v2.1",
```
Run the mock server with `npm start:mock-server` and run tests with `npm run test`

## Causes
Loading a remote context makes ``jsonld`` dependency fail when executing the function ``loadDocument`` in ``documentLoaders/xhr.js``

## Suggestions
Upgrade `jsonld` dependency in `cert-verifier-js`. Haven't tried but maybe could work.

## What we tried
Testing to verifiy a certificate with a remote context certificate in `cert-verifier-js` doesn't cause any problems.

Thanks in advance if you can provide any help!

**Comment by lemoustachiste** [comment]
closing as this is more likely a cert-verifier-js error, reported here: https://github.com/blockchain-certificates/cert-verifier-js/issues/138, bringing previous comment to said task
